plugins {
    id 'base'
    id 'net.fabricmc.fabric-loom' version '1.15.5' apply false
    id 'net.neoforged.moddev' version '2.0.141' apply false
}

group = 'com.wayfarer'

allprojects {
    group = 'com.wayfarer'
    repositories {
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://maven.terraformersmc.com/releases/" }
        maven { url "https://maven.fabricmc.net/" }
        maven {
            name 'Xander Maven'
            url 'https://maven.isxander.dev/releases'
        }
    }
}

tasks.named('build') {
    dependsOn(':common:build', ':fabric:build', ':neoforge:build')
}
